version: "3.8"

services:
  backend:
    build:
      context: ./backend # Path to the backend Dockerfile
    ports:
      - "8081:8081"

  backend2:
    build:
      context: ./backend # Path to the backend Dockerfile
    ports:
      - "8084:8081"

  auth-backend:
    build:
      context: ./auth-backend # Path to the backend Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend/chat-fe # Path to the frontend Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend # Wait for backend service to be ready before starting frontend
