version: "3.8"

services:
  backend:
    image: bapatanuparth/chat-backend:lts
    ports:
      - "8081:8081"

  auth-backend:
    image: bapatanuparth/auth-backend:lts
    ports:
      - "5000:5000"

  frontend:
    image: bapatanuparth/chat-frontend:lts
    ports:
      - "3000:3000"
    depends_on:
      - backend # Wait for backend service to be ready before starting frontend
